
kind: Namespace
apiVersion: v1
metadata:
  name: nodejs-db-project

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nodjs-db
  labels:
    app: backend-nodjs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nodjs-db
  template:
    metadata:
      labels:
        app: backend-nodjs-db
    spec:
      containers:
      - name: backend-nodjs-db
        image: tftest/backend-nodjs-db:latest
        ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: backend-nodjs-db
  labels:
    name: backend-nodjs-db
spec:
  ports:
  - port: 3001
    targetPort: 3001
  clusterIP: None
  selector:
    app: backend-nodjs-db
