
kind: Namespace
apiVersion: v1
metadata:
  name: nodejs-db-project

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nodejs-db
  labels:
    app: frontend-nodejs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nodejs-db
  template:
    metadata:
      labels:
        app: frontend-nodejs-db
    spec:
      containers:
      - name: frontend-nodejs-db
        image: tftest/frontend-nodejs-db:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-nodejs-db
  labels:
    name: frontend-nodejs-db
spec:
  ports:
  - port: 3000
    targetPort: 3000
  clusterIP: None
  selector:
    app: frontend-nodejs-db